[[stack]]
name = "monitoring"
description = "Monitoring stack"
deploy = false
tags = ["prod", "monitoring"]

[stack.config]
swarm = "production-swarm"
file_paths = ["compose.yaml"]
git_provider = "github.com"
git_account = "your-git-account"
repo = "your-org/monitoring-stack"
branch = "main"
environment = """
DOMAIN = [[DOMAIN]]
TZ = [[TZ]]
"""
